/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProvisionRouteImport } from './routes/provision'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as ApiInteractionsRouteImport } from './routes/api/interactions'
import { Route as ApiLocalOpRouteImport } from './routes/api/local-op'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvisionRoute = ProvisionRouteImport.update({
  id: '/provision',
  path: '/provision',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInteractionsRoute = ApiInteractionsRouteImport.update({
  id: '/api/interactions',
  path: '/api/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalOpRoute = ApiLocalOpRouteImport.update({
  id: '/api/local-op',
  path: '/api/local-op',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dispatch': typeof DispatchRoute
  '/login': typeof LoginRoute
  '/provision': typeof ProvisionRoute
  '/security': typeof SecurityRoute
  '/tests': typeof TestsRoute
  '/tickets': typeof TicketsRoute
  '/api/interactions': typeof ApiInteractionsRoute
  '/api/local-op': typeof ApiLocalOpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dispatch': typeof DispatchRoute
  '/login': typeof LoginRoute
  '/provision': typeof ProvisionRoute
  '/security': typeof SecurityRoute
  '/tests': typeof TestsRoute
  '/tickets': typeof TicketsRoute
  '/api/interactions': typeof ApiInteractionsRoute
  '/api/local-op': typeof ApiLocalOpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dispatch': typeof DispatchRoute
  '/login': typeof LoginRoute
  '/provision': typeof ProvisionRoute
  '/security': typeof SecurityRoute
  '/tests': typeof TestsRoute
  '/tickets': typeof TicketsRoute
  '/api/interactions': typeof ApiInteractionsRoute
  '/api/local-op': typeof ApiLocalOpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/dispatch'
    | '/login'
    | '/provision'
    | '/security'
    | '/tests'
    | '/tickets'
    | '/api/interactions'
    | '/api/local-op'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/dispatch'
    | '/login'
    | '/provision'
    | '/security'
    | '/tests'
    | '/tickets'
    | '/api/interactions'
    | '/api/local-op'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/dispatch'
    | '/login'
    | '/provision'
    | '/security'
    | '/tests'
    | '/tickets'
    | '/api/interactions'
    | '/api/local-op'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  DispatchRoute: typeof DispatchRoute
  LoginRoute: typeof LoginRoute
  ProvisionRoute: typeof ProvisionRoute
  SecurityRoute: typeof SecurityRoute
  TestsRoute: typeof TestsRoute
  TicketsRoute: typeof TicketsRoute
  ApiInteractionsRoute: typeof ApiInteractionsRoute
  ApiLocalOpRoute: typeof ApiLocalOpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provision': {
      id: '/provision'
      path: '/provision'
      fullPath: '/provision'
      preLoaderRoute: typeof ProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interactions': {
      id: '/api/interactions'
      path: '/api/interactions'
      fullPath: '/api/interactions'
      preLoaderRoute: typeof ApiInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-op': {
      id: '/api/local-op'
      path: '/api/local-op'
      fullPath: '/api/local-op'
      preLoaderRoute: typeof ApiLocalOpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  DispatchRoute: DispatchRoute,
  LoginRoute: LoginRoute,
  ProvisionRoute: ProvisionRoute,
  SecurityRoute: SecurityRoute,
  TestsRoute: TestsRoute,
  TicketsRoute: TicketsRoute,
  ApiInteractionsRoute: ApiInteractionsRoute,
  ApiLocalOpRoute: ApiLocalOpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
